platform :ios, '13.0'

target 'MVVMGithub' do
  use_frameworks!

  pod 'Alamofire', '~> 5.4.2'

  target 'MVVMGithubTests' do
    inherit! :search_paths
    pod "Nimble", "~> 9.2"
    pod 'Nimble-Snapshots', '~> 9.0.0'
  end

  target 'MVVMGithubUITests' do
    # Pods for testing
  end

end
