# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMGithub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVMGithub

  target 'MVVMGithubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMGithubUITests' do
    # Pods for testing
  end

end
